airbnb/incubator-superset

superset/assets/javascripts/SqlLab/components/ResultSet.jsx
superset/assets/javascripts/SqlLab/components/SqlEditor.jsx
superset/assets/javascripts/SqlLab/main.less
superset/assets/javascripts/components/FilterableTable/FilterableTableStyles.css

Cherry picking #4246
to: @graceguo-supercat @michellethomas

[Sql Lab] Fix query results display at the bottom of screen (#4246)

---

superset/assets/javascripts/chart/Chart.jsx
superset/assets/javascripts/chart/chartAction.js
superset/assets/javascripts/chart/chartReducer.js
superset/assets/javascripts/dashboard/components/Dashboard.jsx
superset/assets/javascripts/dashboard/components/DashboardContainer.jsx
superset/assets/javascripts/dashboard/reducers.js
superset/assets/javascripts/explore/components/ExploreViewContainer.jsx
superset/assets/javascripts/explore/index.jsx
superset/assets/javascripts/explore/reducers/index.js
superset/assets/javascripts/logger.js
superset/assets/spec/helpers/browser.js
superset/models/core.py
superset/views/core.py

add loading log for dash and exploreview
breakdown whole page load action to multiple charts loading events and render events
(cherry picked from commit 724c3f4)

add frontend logging utility function (#4226)

---

superset/assets/javascripts/chart/Chart.jsx
superset/assets/javascripts/chart/chartAction.js
superset/assets/javascripts/explore/components/ExploreViewContainer.jsx
superset/assets/spec/javascripts/chart/Chart_spec.jsx

[Explore] Fix Stop Query Button behavior (#4301)
[Bug] Resize should trigger chart re-render (#4322)

Cherry pick 2 fixes

---

superset/assets/javascripts/chart/Chart.jsx
superset/assets/javascripts/components/Loading.jsx
superset/assets/javascripts/dashboard/components/Dashboard.jsx
superset/assets/javascripts/explore/components/ExploreChartHeader.jsx
superset/assets/spec/javascripts/chart/Chart_spec.jsx
superset/assets/spec/javascripts/dashboard/Dashboard_spec.jsx
superset/assets/spec/javascripts/dashboard/fixtures.jsx
superset/assets/spec/javascripts/dashboard/reducers_spec.js
superset/assets/spec/javascripts/explore/components/ExploreChartHeader_spec.jsx
superset/assets/stylesheets/superset.less
superset/db_engine_specs.py
superset/forms.py
superset/views/core.py
tests/core_tests.py

- [explore] fix missing CacheLabel (#4326)
- Refactor import csv (#4298) 
- [bug] fix JS error when interactive with loading filter_box (#4339)
@michellethomas @john-bodley @timifasubaa

Cherrypick a few fixes

---

superset/db_engine_specs.py
superset/views/core.py
tests/core_tests.py

This cherry picks 
https://github.com/apache/incubator-superset/commit/2d8a0cc6c9342a88a18e145b4b59519cd0aa6c9c and https://github.com/apache/incubator-superset/commit/19a0827d1f4868ebe2f68a51a5e568502444d338 . 
@john-bodley @michellethomas @graceguo-supercat

Cherry pick CSV hotfix and dashboard view

---

superset/connectors/druid/models.py

Cherry picking commit from apache [#4291](https://github.com/apache/incubator-superset/pull/4291/commits/272f40009b561629d00141ec21831d6ef9e796ec)

Fixing json decode error on druiddatasourcemodelview/api/read

---

superset/views/core.py

- [revert] Reverting PR #4062 (#4359)
- Remove permission check for frontend logging API (#4388)
@john-bodley @michellethomas @timifasubaa

cherry pick Log API permission issue

---

superset/assets/javascripts/SqlLab/components/App.jsx
superset/assets/javascripts/SqlLab/components/SqlEditor.jsx
superset/assets/javascripts/SqlLab/components/TabbedSqlEditors.jsx
superset/assets/javascripts/SqlLab/main.less
superset/assets/spec/javascripts/sqllab/SqlEditor_spec.jsx
superset/assets/spec/javascripts/sqllab/TabbedSqlEditors_spec.jsx

[SqlLab] Fix a few height related UI issues #4401
@timifasubaa @michellethomas @john-bodley

Cherry pick Sql Lab bug fixes (#4401)

---

superset/migrations/versions/e866bd2d4976_smaller_grid.py

[hotfix] resolve utf-8 encoding issue in db migration (#4461)

---

superset/assets/javascripts/welcome/App.jsx
superset/viz.py
tests/core_tests.py

This PR cherry picks a couple of necessary fixes which are gating our deployment.
to: @GabeLoins @graceguo-supercat @michellethomas @timifasubaa

cherry pick fixes

---

superset/views/core.py

(cherry picked from commit 369f652)
@michellethomas @john-bodley @timifasubaa

[bug] fix shortener url (#4560)

---

superset/views/core.py

(cherry picked from commit 1e8cd0e61e7bb442af7eab9997da487a82c91673)
to: @GabeLoins @graceguo-supercat @michellethomas

[payload] Set status code on error rather than query status

---

superset/assets/javascripts/explore/components/ExploreViewContainer.jsx
superset/assets/javascripts/explore/index.jsx
superset/assets/javascripts/explore/stores/store.js
superset/jinja_context.py
superset/utils.py
superset/views/core.py
tests/utils_tests.py

* [Explore] Save url parameters when user save slices
(cherry picked from commit 9edbd64)

Cherry Pick: [Explore] Save custom url parameters when user save slices (#4578)

---

superset/assets/package.json

(cherry picked from commit 8951990)

Cherrypick: [BugFix] Resizing widgets problem #4596 (#4597)

---

superset/assets/javascripts/explore/components/controls/TextControl.jsx
superset/assets/visualizations/mapbox.jsx
superset/assets/visualizations/nvd3_vis.js
superset/views/core.py

- [slice_json] pass slice id to get_form_data() (#4607)
- fix mapbox viz (#4621)
- [bug fixes] annotations <> x domains, zeros in text (#4194)
@michellethomas @john-bodley @williaster

cherry pick mapbox and annotation fix

---

.pylintrc
superset/viz.py

(cherry picked from commit b906fece68bee8ccfba4d1f46da2221c37b5d0fa)

Move run_extra_queries outsize of BaseViz init

---

superset/sql_lab.py
tests/sqllab_tests.py

Cherry picking fix for sqllab numpy array
@graceguo-supercat @john-bodley

Cherry pick sqllab numpy

---

superset/assets/javascripts/SqlLab/components/SqlEditor.jsx
superset/assets/javascripts/SqlLab/components/SqlEditorLeftBar.jsx
superset/assets/spec/javascripts/sqllab/SqlEditorLeftBar_spec.jsx
superset/assets/spec/javascripts/sqllab/TabbedSqlEditors_spec.jsx
superset/cli.py
superset/connectors/druid/models.py
superset/connectors/druid/views.py
superset/migrations/versions/e68c4473c581_allow_multi_schema_metadata_fetch.py
superset/migrations/versions/f231d82b9b26_.py
superset/models/core.py
superset/views/core.py
tests/druid_tests.py

This PR cherry-picks the a couple of PRs needed for refreshing Druid metadata. Note 4551 is included for the ride (which will be tested) as it's a pre-requisite for the database migrations.
to: @graceguo-supercat @michellethomas

John bodley cherry pick 4551 4655

---

superset/cli.py
superset/connectors/druid/models.py
superset/connectors/druid/views.py
superset/migrations/versions/f231d82b9b26_.py
tests/druid_tests.py

(cherry picked from commit f9d85bd2e1fd9bc233d19c76bed09467522b968a)

[druid] Updating refresh logic (#4655)

---

superset/viz.py

(cherry picked from commit c94e995d2938fb774835099bf6815929b56fdfc0)

Fix bug with sorting columns in group by using time shift

---

superset/sql_lab.py
superset/views/core.py

Cherry picking #4669 and #4686 to remedy the Jinja issue. 
to: @graceguo-supercat @michellethomas

John bodley cherry picks

---

UPDATING.MD
superset/__init__.py
superset/cli.py
superset/connectors/druid/models.py
superset/connectors/druid/views.py
superset/connectors/sqla/models.py
superset/connectors/sqla/views.py
superset/data/__init__.py
superset/models/core.py
superset/models/helpers.py
superset/models/sql_lab.py
superset/security.py
superset/sql_lab.py
superset/utils.py
superset/views/base.py
superset/views/core.py
tests/access_tests.py
tests/base_tests.py
tests/celery_tests.py
tests/core_tests.py
tests/druid_tests.py
tests/security_tests.py
tests/sqllab_tests.py

Cherry-pick extensible security manager to Superset 
@john-bodley

-Cherrypick security manager refactor

---

superset/connectors/druid/models.py
tests/druid_tests.py

(cherry picked from commit df4ff05441eaac7ca99f5725956f500344bc257d)
to: @graceguo-supercat @michellethomas

[druid] Excluding refreshing verbose name (#4761)

---

superset/db_engine_specs.py

This PR cherry picks https://github.com/apache/incubator-superset/pull/4804
@michellethomas @john-bodley

call next() the right way

---

superset/models/core.py

(cherry picked from commit 89347172d22688d110e24df3cfc35efe77dce45c)

[sql] Using read_sql_query instead of read_sql (#4853)

---

superset/assets/visualizations/markup.js
superset/models/core.py
tests/model_tests.py

This PR cherry picks in the following PRS:
- #5060
- #5062

[cherry-picks] Picking cherries

---

superset/models/core.py
tests/model_tests.py

(cherry picked from commit 0511d1f38d99d98bcc0d179e0578d20f4d4c2985)

[get_df] Adding support for multi-statement SQL (#5086)

---

superset/viz.py
tests/viz_tests.py

Cherry picks a couple of PRs that fix issues with adhoc metrics 
#5026 (cherry picked from commit 9f66dae328b70b277bfc0e1f47c3f63aff541ae4)
#5080 (cherry picked from commit c18ef8903409c20b8526b9acd12d3ba1c4c3664b)
@john-bodley @graceguo-supercat @timifasubaa

cherry-pick adhoc metric bugfixes

---

superset/assets/spec/javascripts/explore/components/AdhocFilterEditPopoverSimpleTabContent_spec.jsx
superset/assets/src/components/MetricOption.jsx
superset/assets/src/explore/AdhocFilter.js
superset/assets/src/explore/components/AdhocFilterEditPopoverSimpleTabContent.jsx
superset/assets/src/explore/constants.js
superset/assets/src/visualizations/time_table.jsx
superset/connectors/sqla/views.py
superset/migrations/versions/c5756bec8b47_time_grain_sqla.py

- fixing LIKE constant name (#5110) (cherry picked from commit f3778c3c81b1e9a04869708b8206daf7734a0fa7)
- [crud] Improving performance (#5136) (cherry picked from commit f102eab33ce3a7246da267786ec07c391c6662d6)
- Fixing time table viz for adhoc metrics (#5117) (cherry picked from commit ff4b103025841424495fdcdbed2b67a006746ecf)
- adding null checks to adhoc filter popover (#5111) (cherry picked from commit 40fadfcb4f7decc364f3f875fcd5723d81145ad8)
@john-bodley @graceguo-supercat @timifasubaa

Cherry picking fixes for may merge

---

superset/assets/.istanbul.yml
superset/assets/src/explore/controls.jsx
superset/assets/src/visualizations/heatmap.js
superset/assets/src/visualizations/nvd3_vis.js
superset/assets/src/visualizations/table.js
superset/connectors/druid/models.py
superset/connectors/sqla/models.py
superset/data/__init__.py
superset/viz.py

Cherry picking a few fixes
Fixing tooltip displaying metrics in heatmap (#5055) (cherry picked from commit 280200f8341757923aef1a1de9cf8b174c16cd66)
fix empty metrics (cherry picked from commit 95bb1753ab3a9fef572b40d7b7762fd7b4982374)
Repoint .istambul.yml to the right location (#5187) (cherry picked from commit 30111bf3fd706963bb690a340eded707b251e8d9)
Introduce class attr BaseViz.enforce_numerical_metrics (#5176) (cherry picked from commit a1095437bc11fa29986f8d283a887d44343b22d3)
fix Formula type annotation, it doesn't show up since #4630 (#5181) (cherry picked from commit 585dbe663841052a07561c2c67509d104a854211)
@graceguo-supercat @timifasubaa @john-bodley

Cherry pick annotations empty metrics

---

superset/assets/src/explore/controls.jsx
superset/connectors/druid/views.py
superset/db_engine_specs.py
superset/views/core.py
superset/viz.py

This PR cherry-picks a few bug fixes and performance changes.

cherry picks

---

superset/connectors/druid/views.py
superset/connectors/sqla/views.py
superset/views/core.py
superset/viz.py
tests/viz_tests.py

Cherry-picking https://github.com/apache/incubator-superset/pull/5315. 
to: @graceguo-supercat @michellethomas @timifasubaa @williaster

[cherry pick] cache timeout fix

---

superset/assets/src/dashboard/deprecated/v1/components/Controls.jsx
superset/assets/src/dashboard/deprecated/v1/components/Dashboard.jsx
superset/assets/src/dashboard/deprecated/v1/components/Header.jsx
superset/views/core.py

@williaster @michellethomas @timifasubaa

[dashboard transition] Cherry pick fix for dashboard force v2 edit

---

superset/assets/src/explore/controls.jsx
superset/assets/src/explore/store.js
superset/migrations/versions/bddc498dd179_adhoc_filters.py
superset/models/core.py
superset/utils.py
superset/views/core.py
superset/viz.py
tests/utils_tests.py
tests/viz_tests.py

This PR cherry-picks a few PRs related to a number of bugs which have surfaced recently.

[cherries] Cherry picking a few bug fixes

---

superset/views/core.py

(cherry picked from commit e52518c3cd3eb623f451c0d5ea1d6608654f84fa)

[ad-hoc filters] Remove legacy split in /explore (#5533)

---

superset/views/core.py

(cherry picked from commit b564aa43dce84790642de8a8abfd0b2ddf7a6507)

Stop pretty printing dashboard json (#5538)

---

superset/__init__.py
superset/assets/.babelrc
superset/assets/.eslintrc
superset/assets/.istanbul.yml
superset/assets/package.json
superset/assets/spec/helpers/browser.js
superset/assets/spec/javascripts/chart/Chart_spec.jsx
superset/assets/src/chart/Chart.jsx
superset/assets/src/components/Loading.jsx
superset/assets/src/dashboard/components/SliceHeader.jsx
superset/assets/src/visualizations/index.js
superset/assets/src/visualizations/markup.js
superset/assets/webpack.config.js
superset/assets/yarn.lock
superset/templates/superset/base.html
superset/templates/superset/basic.html
superset/templates/superset/partials/_script_tag.html
superset/viz.py

This PR cherry picks [[webpack 4] third time's the charm ;) #5370](https://github.com/apache/incubator-superset/pull/5370) 
@graceguo-supercat @michellethomas @john-bodley

[webpack 4] cherry pick

---

superset/assets/src/explore/controls.jsx
superset/config.py
superset/connectors/sqla/models.py
superset/migrations/versions/0c5070e96b57_add_user_attributes_table.py
superset/migrations/versions/1a1d627ebd8e_position_json.py
superset/models/__init__.py
superset/models/core.py
superset/models/user_attributes.py
superset/utils.py
superset/views/core.py
tests/utils_tests.py

This PR picks a few cherries related to recent bug fixes. Note that I needed to pick #5550 to preserve the DB migration lineage. This feature is disabled by default. 

[cherries] Picking a few cherries

---

superset/assets/spec/javascripts/visualizations/nvd3_viz_spec.jsx
superset/assets/src/dashboard/reducers/getInitialState.js
superset/assets/src/dashboard/util/constants.js
superset/assets/src/dashboard/util/newComponentFactory.js
superset/assets/src/modules/colors.js
superset/assets/src/utils/common.js
superset/assets/src/visualizations/nvd3_vis.css
superset/assets/src/visualizations/nvd3_vis.js
superset/config.py
superset/views/core.py
superset/viz.py

this PR cherrypick following prs from Superset master:
Dashboard related:
[Dashobard]Fix bad merge (#5624)
set default layout for new added charts (#5425)
Remove dashboard transition related config (#5505)
This feature improves line type for timeshift chart:
Improve time shift (#5140)
@michellethomas @john-bodley @timifasubaa

Cherrypick a few dash fixes

---

superset/assets/spec/javascripts/visualizations/nvd3_viz_spec.jsx
superset/assets/src/modules/colors.js
superset/assets/src/utils/common.js
superset/assets/src/visualizations/nvd3_vis.css
superset/assets/src/visualizations/nvd3_vis.js
superset/viz.py

#5140 has other dependencies that are not available in airbnb-master. have to rollback for now.
@michellethomas @john-bodley

Rollback cherrypick #5140

---

superset/assets/src/visualizations/nvd3_vis.js

This PR cherry-picks a couple of issues related to tooltips.
to: @conglei @graceguo-supercat @kristw @michellethomas @timifasubaa @williaster

[cherry-picks] Picking a few tooltip fixes

---

superset/assets/spec/javascripts/explore/components/DisplayQueryButton_spec.jsx
superset/assets/src/explore/components/DisplayQueryButton.jsx
superset/assets/src/explore/visTypes.jsx
superset/assets/src/visualizations/line_multi.js
superset/connectors/sqla/views.py

Cherry-pick the following commit(s):
SHA | Time | Log | Author
--- | --- | --- | ---
1d7f4f28 | Tue Aug 14 10:48:21 2018 -0700 | [bugfix] line_multi chart crashed on chosen (#5568) (#5572) | [Krist Wongsuphasawat]
ad469c72 | Mon Aug 6 17:27:48 2018 -0700 | Fixed the wrong icon for Source -> Table (#5574) | [Conglei]
@graceguo-supercat @michellethomas @john-bodley @williaster

Cherry-pick(s): Bugfix multi-line chart and icon + unit test

---

superset/assets/src/explore/components/ExploreViewContainer.jsx
superset/assets/src/explore/controls.jsx
superset/assets/src/explore/store.js
superset/assets/src/explore/visTypes.jsx
superset/views/core.py
tests/core_tests.py

* Fixing issue with extra params in formData
* Pass in param use_slice_data to decide whether to use slice data
* Fixing core_tests to not use explore_json overrides
(cherry picked from commit bf0afef7a9b0212e339d823b632a7e2ddbf46f6d)

Fix form data issue switching viz types (#5100)

---

superset/views/core.py

(cherry picked from commit 492ad6c49ac965c2956c46bae13aefbef6b870d8)

use_slice_data in slice_json calls (#5643)

---

superset/assets/src/SqlLab/components/CopyQueryTabUrl.jsx
superset/assets/src/SqlLab/components/SouthPane.jsx
superset/assets/src/SqlLab/components/SqlEditorLeftBar.jsx
superset/assets/src/SqlLab/components/TabbedSqlEditors.jsx
superset/assets/src/SqlLab/components/TableElement.jsx
superset/assets/src/SqlLab/components/TemplateParamsEditor.jsx
superset/assets/src/SqlLab/main.less
superset/assets/src/SqlLab/reducers.js
superset/assets/src/reduxUtils.js

Cherry-pick the following commit(s):
SHA | Time | Log | Author
--- | --- | --- | ---
cdd348ab | Sun Aug 19 22:43:00 2018 -0700 | Minor improvements to SQL Lab UI (#5662) (origin/master, origin/HEAD, apache/master, master) | [Krist Wongsuphasawat]
3d15d910 | Fri Aug 17 17:44:56 2018 -0700 | [sqllab] call out transient state of tabs to users (#5652) | [Chris Williams]
@john-bodley @conglei @graceguo-supercat @kristw @michellethomas @timifasubaa @williaster

Cherry-picks: Update SQL Lab

---

superset/assets/src/explore/controls.jsx
superset/assets/src/explore/visTypes.jsx
superset/assets/src/visualizations/nvd3_vis.js

This PR cherry-picks https://github.com/apache/incubator-superset/pull/5236 which fixes an issue with the pie chart.
to: @graceguo-supercat @kristw @michellethomas @timifasubaa @williaster

[pie] improvements to pie charts (#5236)

---

superset/connectors/druid/models.py
superset/connectors/sqla/models.py
superset/models/core.py
superset/models/helpers.py
superset/security.py

(cherry picked from commit 89927558e85cd121b46818cb2f38d3a2e61e25d6)

[security] Moving set/merge perm to security manager (#5684)

---

superset/sql_parse.py
tests/sql_parse_tests.py

(cherry picked from commit 5c49514e2f18ac18b16e3befe9c4b9b900b49908)

[sqlparse] fix sqlparse bug (#5703)

---

superset/utils.py

(cherry picked from commit 52b99dff7838868ff721c8a22081092f24bee3ef)

[celery] Using preferred configuration proceedure (#5726)

---

superset/assets/package.json
superset/assets/src/explore/visTypes.jsx
superset/assets/src/visualizations/BigNumber.jsx
superset/assets/src/visualizations/HorizonChart.css
superset/assets/yarn.lock

Cherry-pick the following commit(s):
SHA | Time | Log | Author
--- | --- | --- | ---
0781cf2c | Mon Aug 27 15:46:52 2018 -0700 | [bugfix] BigNumber crash, Horizon indent and Myanmar geojson (#5746) (apache/master) | Krist Wongsuphasawat
b92e7308 | Wed Aug 22 10:27:19 2018 -0700 | Allow users to select color for big number (#5694) | Hugh A. Miles II
@john-bodley @conglei @graceguo-supercat @kristw @michellethomas @timifasubaa @williaster

Cherry-picks: Allow users to choose color for BigNumber

---

superset/utils.py

(cherry picked from commit cf12ea0f03f01a52646145f3f797071c5e6b881b)

[celery] setting default (#5812)

---

superset/assets/src/components/StackTraceMessage.jsx
superset/sql_lab.py
superset/views/core.py

This PR adds 
https://github.com/apache/incubator-superset/pull/5862
https://github.com/apache/incubator-superset/pull/5859
https://github.com/apache/incubator-superset/pull/5844
@airbnb/superset-fork-maintainers

Add sqllab logging and new tab for access requests.

---

requirements.txt
setup.py
superset/utils.py
superset/views/core.py

This PR bumps the simplejson version to fix a regression on staging. 
@airbnb/superset-fork-maintainers

cherry pick #5121

---

superset/sql_lab.py

(cherry picked from commit 6f87552bc26b3e6ea5b878acdabba20a0e142e98)

[sqllab] fix unexpected keyword argument 'ignore_nan' (#5490)

---

requirements.txt
setup.py
superset/db_engine_specs.py

This PR adds some more CSV changes
1. It infers the column type in the CSV files (#5267)
2. It quotes the column names (#5368)
3. It fixes csv schema_name upload bugs (#5940)
tested on devbox
@airbnb/superset-fork-maintainers

Cherrypick more csv changes

---

superset/connectors/sqla/models.py
superset/connectors/sqla/views.py
superset/db_engine_specs.py
superset/templates/superset/ajah.html
superset/views/core.py
tests/core_tests.py

This PR picks a couple of recent PRs.

[cherry picks] Picking a couple of ripe cherries

---

superset/assets/src/dashboard/stylesheets/dashboard.less
superset/utils.py

cherry pick from #6037 #5764
(cherry picked from commit 361f588)
(cherry picked from commit 6c6ea37)
@michellethomas @john-bodley @kristw

[Cherrypick] a couple of bug fixes

---

superset/assets/spec/javascripts/explore/components/RowCountLabel_spec.jsx
superset/assets/src/SqlLab/actions.js
superset/assets/src/SqlLab/components/ShareSqlLabQuery.jsx
superset/assets/src/chart/chartAction.js
superset/assets/src/components/AsyncSelect.jsx
superset/assets/src/datasource/DatasourceEditor.jsx
superset/assets/src/datasource/DatasourceModal.jsx
superset/assets/src/explore/components/DisplayQueryButton.jsx
superset/assets/src/explore/components/RowCountLabel.jsx
superset/assets/src/explore/components/controls/AnnotationLayer.jsx
superset/assets/src/explore/components/controls/MetricsControl.jsx
superset/assets/src/utils/common.js
superset/assets/src/utils/getClientErrorObject.js
superset/utils/core.py
superset/views/core.py

cherrypick more fixes since last merge:
#6286
#6277
#6252
#6269
#6276
@michellethomas @john-bodley @timifasubaa @kristw @williaster

Apache sync: cherrypick fixes 

---

superset/assets/src/dashboard/actions/dashboardState.js

This cherry-picks the commits from [apache #6349](https://github.com/apache/incubator-superset/pull/6349)
@kristw @michellethomas @graceguo-supercat

[bugfix] don't parse save dashboard response

---

superset/assets/src/dashboard/actions/dashboardState.js
superset/assets/src/visualizations/nvd3/transformProps.js
superset/views/core.py

Cherry-pick the following commit(s):
SHA | Time | Log | Author
--- | --- | --- | ---
5a377322 | Fri Nov 9 11:06:30 2018 -0800 | change to camelcase (#6354) | Krist Wongsuphasawat
8bf9a5b9 | Fri Nov 9 11:15:42 2018 -0800 | [dashboard] fix save/save-as flow (#6350)  | Chris Williams
@john-bodley @conglei @graceguo-supercat @kristw @michellethomas @timifasubaa @williaster

[bugfix] chart legend verbose name

---

superset/viz.py

* fixed the cache issue for bignumber
(cherry picked from commit 8e2d28dd6e057a16cd621bdf32c4798a2dd7ef61)
@timifasubaa @graceguo-supercat

Fixed the cache issue for BigNumber (#6375)

---

superset/assets/src/dashboard/containers/DashboardComponent.jsx
superset/db_engine_specs.py
superset/migrations/versions/4ce8df208545_migrate_time_range_for_default_filters.py

cherry pick #6357, #6393, #6378
@john-bodley @michellethomas @kristw @timifasubaa

[sync] cherrypick migration, hive, dashboard fix

---

superset/assets/src/chart/Chart.jsx
superset/assets/src/dashboard/actions/datasources.js
superset/assets/src/explore/components/ExploreChartHeader.jsx
superset/assets/src/explore/components/ExploreViewContainer.jsx

cherrypick #6442 #6438
@michellethomas @john-bodley @timifasubaa @williaster

[sync] cherrypick js error logging and explore view bug

---

requirements.txt
setup.py

Choose one
Replace the pinned commit with the actual FAB release for the permissions perf fix
test in staging
@michellethomas @john-bodley

Upgrade FAB to 2.1.6

---

superset/assets/spec/javascripts/dashboard/components/gridComponents/Tabs_spec.jsx
superset/assets/src/components/AnchorLink.jsx
superset/assets/src/components/URLShortLinkButton.jsx
superset/assets/src/dashboard/components/gridComponents/Tabs.jsx

cherrypick [open source PR #7812](https://github.com/apache/incubator-superset/pull/7812) to airbnb-master
(cherry picked from commit 9b8996038e0ff02f8902cdb8e1822d8000f79210)
Choose one
@michellethomas @etr2460 @john-bodley

[cherrypick][dashboard] Fix URLShortLinkButton position after click anchor link

---

superset/assets/src/SqlLab/main.less

Choose one
Cherrypick https://github.com/apache/incubator-superset/pull/7674
make sure you can scroll in query search
@graceguo-supercat @michellethomas

Fixed SQL Lab Query Search scrolling issue(#7526) (#7674)

---

superset/connectors/druid/models.py
tests/druid_func_tests.py

(cherry picked from commit 6b9790c8b198f4968cc6359f38a50e769f9ec09e)
Choose one
to: @etr2460 @michellethomas @graceguo-supercat

[ad-hoc] Fixing type for count distinct (#7573)

---

superset/security.py
superset/sql_parse.py
tests/sql_parse_tests.py

Choose one
Cherry picking a couple of bug fixes:
- https://github.com/apache/incubator-superset/pull/7374
- https://github.com/apache/incubator-superset/pull/7490
CI.
to: @etr2460 @graceguo-supercat @michellethomas

[cherries] Picking a couple of SQL parsing cherries

---

superset/connectors/sqla/models.py
tests/model_tests.py

Choose one
This PR cherry-picks https://github.com/apache/incubator-superset/pull/7888. Note due to Black changes this is actually a manual replication rather than an explicit cherry-pick.
CI.
to: @graceguo-supercat @michellethomas @williaster

[cherry] Picking #7888

---

superset/assets/package-lock.json
superset/assets/package.json
superset/assets/spec/javascripts/components/TableSelector_spec.jsx
superset/assets/src/components/TableSelector.jsx

Choose one
Cherry picks for https://github.com/apache/incubator-superset/pull/7868 and https://github.com/apache/incubator-superset/pull/7915
See previous PRs
CI
@michellethomas @graceguo-supercat @john-bodley

Fix TableSelector perf and responsive y axis

---

superset/connectors/sqla/models.py
tests/model_tests.py

Choose one
This is a cherry-pick of https://github.com/apache/incubator-superset/pull/7933
CI.
to: @etr2460 @graceguo-supercat @michellethomas

[cherry-pick] Picking #7933

---

superset/assets/package-lock.json
superset/assets/package.json

Choose one
Picks #7932 to fix y axis bounds
CI
@graceguo-supercat @john-bodley

Bump nvd3 chart plugin (#7932)

---

docs/installation.rst
superset/assets/package-lock.json
superset/assets/package.json
superset/db_engine_specs/presto.py
superset/views/database/__init__.py
tests/db_engine_specs_test.py

add rc1 to release--0.34 feature branch
@etr2460 @michellethomas @john-bodley

add rc1 to release 0.34 feature branch

---

.travis.yml
tox.ini

Choose one
Cherry-picking a few PRs to resolve the Travis issues. 
CI.
to: @etr2460 @graceguo-supercat @michellethomas

[cherry] Picking a few cherries to remedy the Travis issues

---

superset/__init__.py

Choose one
This PR emulates cherry-picking of https://github.com/apache/incubator-superset/pull/7992 (actual cherry-picking isn't viable because of the Black formatting). 
CI. 
to: @etr2460 @graceguo-supercat @michellethomas

[cherry] Emulating cherry-picking of 7992

---

superset/__init__.py
superset/assets/spec/javascripts/dashboard/components/HeaderActionsDropdown_spec.jsx
superset/assets/spec/javascripts/dashboard/components/RefreshIntervalModal_spec.jsx
superset/assets/src/SqlLab/actions/sqlLab.js
superset/assets/src/dashboard/actions/dashboardState.js
superset/assets/src/dashboard/components/HeaderActionsDropdown.jsx
superset/assets/src/dashboard/components/RefreshIntervalModal.jsx
superset/assets/src/dashboard/reducers/dashboardState.js

cherrypick #8014 #7955
revert #7992

cherrypick a few fixes from open source

---

superset/assets/src/explore/components/ExploreViewContainer.jsx
superset/db_engine_specs/presto.py
tests/db_engine_specs_test.py

cherrypick #8075 #8070 onto airbnb release 0.34
@etr2460 @michellethomas

cherry pick bug fixes

---

superset/assets/stylesheets/less/index.less

Revert #7822 from airbnb release branch.
CI and manual test.
@etr2460 @serenajiang @michellethomas

[Revert] Line chart tooltips broken on Firefox #7822
